version: '3.1'
services:
  web:
    build: docker/nginx
    ports: 
      - 8000:80
    links: 
      - php
    volumes:
      - .:/var/www/html
  php:
    build: docker/php
    links:
      - db
      - redis
    volumes:
      - .:/var/www/html
  db:
    image: postgres:11
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 3306:3306
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=symfonytest
  redis:
    image: redis:3.2
